import os

def generar_dominio(dominios):
    file = open("dominios.txt", "w")

    for dominio in dominios:
        domi = "create table sisdep_general." + dominio +" (\n" \
               "    id bigserial primary key,\n"\
               "    descripcion varchar\n" \
               ")"
        file.write(domi + os.linesep)

    file.close()

dominios = [
    'tipo_documento',
    'nacionalidad',
    'sexo',
    'tipo_persona',
    'estado_civil',
    'proteccion_constitucional',
    'municipio',
    'tipo_capacidad_diferencial',
    'capacidad_diferencial',
    'escolaridad',
    'parentesco',
    'ocupacion',
    'tipo_ocupacion',
    'tipo_afiliacion',
    'tipo_necesidad',
    'actividad_prohibida',
    'sitio_prohibido',
    'tipo_sensibilizacion',
    'tipo_misional',
    'jornada',
    'procedimiento_anterior',
    'tipo_miembro_sector_interno',
    'persona_atiende',
    'clase_venta',
    'actividad_economica_tipologia',
    'tenencia_propiedad',
    'tipo_modulo',
    'estado',
    'tipo_conexion_servicio',
    'cubierta',
    'material_amueblamiento',
    'tipo_oferta',
    'tipo_visita',
    'tipo_vehiculo',
    'causal_estudio',
    'motivo_autorizacion',
    'tipologia_original',
    'tipo_notificacion',
    'tipo_recurso',
    'grupo_poblacional',
    'grupo_comunitario',
    'motivo_labora_espacio_publico',
    'tipo_pobreza',
    'obtencion_propiedad',
    'tipo_vivienda',
    'material_techo',
    'material_piso',
    'material_pared',
    'servicio_publico',
    'entidad_jubilacion',
    'eps',
    'tipo_cotiza',
    'fondo_pension',
    'arl',
    'tipologia_familiar',
    'ixi_anexo',
    'motivo_recuperacion',
    'tipo_infraccion',
    'tipo_solicitud',
    'tipo_publicidad',
    'aviso_publicitario',
    'tipo_permanencia',
    'tipo_instalacion',
    'aviso_publicitario_apro_economico',
    'finalidad_valla',
    'item_valla',
    'indicador_parametro',
    'item_elemeto_publicitario',
    'elemento_medicion',
    'resultado_visita_pev',
    'tipo_evidencia',
    'motivo_intervencion_infraestructura',
    'tipologia_transitoria',
    'dia_semana',
    'resuelve_resolucion',
    'convenio',
    'orientacion',
    'tipo_modulo_otro',
    'nomenclatura_vial',
    'entidad_apoyo_operativa',
    'programa_o_entidad',
    'tipo_conocimiento',
    'remision_oferta',
    'actividad_operativa',
    'estado_autorizacion',
]

generar_dominio(dominios)
